const fixtureParameters = {
    'Uplighting': [
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Macros', abbr: '▶️' },
        { name: 'Macro Speed', abbr: '⏩' },
        { name: 'Red', abbr: '🔴' },
        { name: 'Green', abbr: '🟢' },
        { name: 'Blue', abbr: '🔵' },
        { name: 'White', abbr: '⚪️' }
    ],
    'Flood': [
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Macros', abbr: '▶️' },
        { name: 'Macro Speed', abbr: '⏩' },
        { name: 'Warm', abbr: '🟡' },
        { name: 'White', abbr: '⚪️' }
    ],
    'BoxLight': [
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Strobe', abbr: '⚡' },
        { name: '', abbr: '' }
    ],
    'LED': [
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Red', abbr: '🔴' },
        { name: 'Green', abbr: '🟢' },
        { name: 'Blue', abbr: '🔵' },
        { name: 'White', abbr: '⚪️' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Macros', abbr: '▶️' },
        { name: 'Speed', abbr: '⏩' }
    ],
    'Par': [
        { name: 'Red', abbr: '🔴' },
        { name: 'Green', abbr: '🟢' },
        { name: 'Blue', abbr: '🔵' },
        { name: 'White', abbr: '⚪️' },
        { name: 'Colors', abbr: '🎨' },
        { name: 'Macros', abbr: '▶️' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Speed', abbr: '⏩' },
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Strobe', abbr: '⚡' }
    ],
    'Tree': [
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Macros', abbr: '▶️' },
        { name: 'Macro Speed', abbr: '⏩' },
        { name: 'Red', abbr: '🔴' },
        { name: 'Green', abbr: '🟢' },
        { name: 'Blue', abbr: '🔵' },
        { name: 'White', abbr: '⚪️' }
    ],
    'Tube Light': [
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Color Macros', abbr: '▶️' },
        { name: 'Background Color', abbr: 'BC' },
        { name: 'Background Shutter', abbr: 'BS' },
        { name: 'Macros', abbr: '▶️' },
        { name: 'Macro Speed', abbr: '⏩' },
        { name: 'Red', abbr: '🔴' },
        { name: 'Green', abbr: '🟢' },
        { name: 'Blue', abbr: '🔵' },
        { name: 'White', abbr: '⚪️' },
        { name: 'Warm White', abbr: '🟡' }
    ],
    'Motorized Par': [
        { name: 'Colors', abbr: '🎨' },
        { name: 'Strobe', abbr: '⚡' },
        { name: 'Shutter', abbr: '(💡)' },
        { name: 'Gobos', abbr: '⭐️' },
        { name: 'Prism', abbr: '🌟' },
        { name: 'Prism Rotate', abbr: '💫' },
        { name: 'Fan Out', abbr: '✨' },
        { name: 'Blur', abbr: '🌫' },
        { name: 'Focus', abbr: '🎯' },
        { name: 'Pan', abbr: '↔️' },
        { name: 'Small Pan', abbr: '🤏🏻' },
        { name: 'Tilt', abbr: '↕️' },
        { name: 'Small Tilt', abbr: '🤏🏻' },
        { name: 'Gobo Macros', abbr: '▶️' },
        { name: 'Reset', abbr: '💾' },
        { name: 'Unknown 1', abbr: '?' },
        { name: 'Unknown 2', abbr: '?' },
        { name: 'Unknown 3', abbr: '?' },
        { name: 'Unknown 4', abbr: '?' },
        { name: 'Unknown 5', abbr: '?' }
    ]
};

const blackBoxFixtures = [
    { name: "Gobo - 2.1", type: 'Motorized Par', from: 1, to: 20 },
    { name: "Gobo - 2.2", type: 'Motorized Par', from: 21, to: 40 },
    { name: "Gobo - 2.3", type: 'Motorized Par', from: 41, to: 60 },
    { name: "Gobo - 2.4", type: 'Motorized Par', from: 61, to: 80 },
    { name: "Gobo - 1.1", type: 'Motorized Par', from: 81, to: 100 },
    { name: "Gobo - 1.2", type: 'Motorized Par', from: 101, to: 120 },
    { name: "Gobo - 1.3", type: 'Motorized Par', from: 121, to: 140 },
    { name: "Gobo - 1.4", type: 'Motorized Par', from: 141, to: 160 },
    { name: "Box Lights row 3", type: 'BoxLight', from: 161, to: 163 },
    { name: "Box Lights row 2", type: 'BoxLight', from: 164, to: 166 },
    { name: "Box Lights row 1", type: 'BoxLight', from: 167, to: 169 },
    { name: "LED - 2.1", type: 'LED', from: 170, to: 177 },
    { name: "LED - 2.2", type: 'LED', from: 178, to: 185 },
    { name: "LED - 2.3", type: 'LED', from: 186, to: 193 },
    { name: "LED - 2.4", type: 'LED', from: 194, to: 201 },
    { name: "LED - 2.5", type: 'LED', from: 202, to: 209 },
    { name: "LED - 2.6", type: 'LED', from: 210, to: 217 },
    { name: "LED - R.3", type: 'LED', from: 218, to: 225 },
    { name: "LED - R.2", type: 'LED', from: 226, to: 233 },
    { name: "LED - R.1", type: 'LED', from: 234, to: 241 },
    { name: "LED - 1.6", type: 'LED', from: 242, to: 249 },
    { name: "LED - 1.5", type: 'LED', from: 250, to: 257 },
    { name: "LED - 1.4", type: 'LED', from: 258, to: 265 },
    { name: "LED - 1.3", type: 'LED', from: 266, to: 273 },
    { name: "LED - 1.2", type: 'LED', from: 274, to: 281 },
    { name: "LED - 1.1", type: 'LED', from: 282, to: 289 },
    { name: "LED - L.1", type: 'LED', from: 290, to: 297 },
    { name: "LED - L.2", type: 'LED', from: 298, to: 305 },
    { name: "LED - L.3", type: 'LED', from: 306, to: 313 },
    { name: "LED - 3.1", type: 'LED', from: 314, to: 321 },
    { name: "LED - 3.2", type: 'LED', from: 322, to: 329 },
    { name: "LED - 3.3", type: 'LED', from: 330, to: 337 },
    { name: "LED - 3.4", type: 'LED', from: 338, to: 345 },
    { name: "LED - 3.5", type: 'LED', from: 346, to: 353 },
    { name: "LED - 3.6", type: 'LED', from: 354, to: 361 },
    { name: "Par - R.4", type: 'Par', from: 362, to: 370 },
    { name: "Par - R.3", type: 'Par', from: 371, to: 379 },
    { name: "Par - R.2", type: 'Par', from: 380, to: 388 },
    { name: "Par - R.1", type: 'Par', from: 389, to: 397 },
    { name: "Par - 1.4", type: 'Par', from: 398, to: 406 },
    { name: "Par - 1.3", type: 'Par', from: 407, to: 415 },
    { name: "Par - 1.2", type: 'Par', from: 416, to: 424 },
    { name: "Par - 1.1", type: 'Par', from: 425, to: 433 },
    { name: "Par - L.1", type: 'Par', from: 434, to: 442 },
    { name: "Par - L.2", type: 'Par', from: 443, to: 451 },
    { name: "Par - L.3", type: 'Par', from: 452, to: 460 },
    { name: "Par - L.4", type: 'Par', from: 461, to: 469 },
    { name: "Par - 3.1", type: 'Par', from: 470, to: 478 },
    { name: "Par - 3.2", type: 'Par', from: 479, to: 487 },
    { name: "Par - 3.3", type: 'Par', from: 488, to: 496 },
    { name: "Par - 3.4", type: 'Par', from: 497, to: 505 },
    { name: "LED Tree", type: 'Tree', from: 506, to: 512 }
];

const auditoriumFixtures = [
    { name: "New lights were installed in the auditorium.", type: 'LED', from: 1, to: 16 },
    { name: "They have yet to be configured / mapped.", type: 'LED', from: 17, to: 32 }
];

const mobileFixtures = [
    { name: "Uplighting", type: 'Uplighting', from: 1, to: 8 },
    { name: "Uplighting", type: 'Uplighting', from: 9, to: 16 },
    { name: "Uplighting", type: 'Uplighting', from: 17, to: 24 },
    { name: "Uplighting", type: 'Uplighting', from: 25, to: 32 },
    { name: "Uplighting", type: 'Uplighting', from: 33, to: 40 },
    { name: "Uplighting", type: 'Uplighting', from: 41, to: 48 },
    { name: "Uplighting", type: 'Uplighting', from: 49, to: 56 },
    { name: "Uplighting", type: 'Uplighting', from: 57, to: 64 },
    { name: "Uplighting", type: 'Uplighting', from: 65, to: 72 },
    { name: "Uplighting", type: 'Uplighting', from: 73, to: 80 },
    { name: "Uplighting", type: 'Uplighting', from: 81, to: 88 },
    { name: "Uplighting", type: 'Uplighting', from: 89, to: 96 },
    { name: "Flood", type: 'Flood', from: 97, to: 102 },
    { name: "BandLED", type: 'LED', from: 103, to: 110 },
    { name: "BandLED", type: 'LED', from: 111, to: 118 },
    { name: "BandLED", type: 'LED', from: 119, to: 126 },
    { name: "BandLED", type: 'LED', from: 127, to: 134 },
    { name: "BandLED", type: 'LED', from: 135, to: 142 },
    { name: "BandLED", type: 'LED', from: 143, to: 150 },
    { name: "DramaLED", type: 'LED', from: 151, to: 158 },
    { name: "DramaLED", type: 'LED', from: 159, to: 166 },
    { name: "DramaLED", type: 'LED', from: 167, to: 174 },
    { name: "DramaLED", type: 'LED', from: 175, to: 182 },
    { name: "DramaLED", type: 'LED', from: 183, to: 190 },
    { name: "DramaLED", type: 'LED', from: 191, to: 198 },
    { name: "Tree 1", type: 'Tree', from: 199, to: 206 },
    { name: "Tree 1", type: 'Tree', from: 207, to: 214 },
    { name: "Tree 1", type: 'Tree', from: 215, to: 222 },
    { name: "Tree 1", type: 'Tree', from: 223, to: 230 },
    { name: "Tree 1", type: 'Tree', from: 231, to: 238 },
    { name: "Tree 1", type: 'Tree', from: 239, to: 246 },
    { name: "Tree 1", type: 'Tree', from: 247, to: 254 },
    { name: "Tree 1", type: 'Tree', from: 255, to: 262 },
    { name: "Tree 1", type: 'Tree', from: 263, to: 270 },
    { name: "Tree 1", type: 'Tree', from: 279, to: 286 },
    { name: "Tree 2", type: 'Tree', from: 287, to: 294 },
    { name: "Tree 2", type: 'Tree', from: 295, to: 302 },
    { name: "Tree 2", type: 'Tree', from: 303, to: 310 },
    { name: "Tree 2", type: 'Tree', from: 311, to: 318 },
    { name: "Tree 2", type: 'Tree', from: 319, to: 326 },
    { name: "Tree 2", type: 'Tree', from: 327, to: 334 },
    { name: "Tree 2", type: 'Tree', from: 335, to: 342 },
    { name: "Tree 2", type: 'Tree', from: 343, to: 350 },
    { name: "Tree 2", type: 'Tree', from: 351, to: 358 },
    { name: "Tube Light 1", type: 'Tube Light', from: 365, to: 376 },
    { name: "Tube Light 2", type: 'Tube Light', from: 377, to: 388 },
    { name: "Tube Light 3", type: 'Tube Light', from: 389, to: 400 },
    { name: "Tube Light 4", type: 'Tube Light', from: 401, to: 412 },
    { name: "Tube Light 5", type: 'Tube Light', from: 413, to: 424 },
    { name: "Tube Light 6", type: 'Tube Light', from: 425, to: 436 },
    { name: "Tube Light 7", type: 'Tube Light', from: 437, to: 448 },
    { name: "Tube Light 8", type: 'Tube Light', from: 449, to: 460 }
];