const instrumentData = {
    'Woodwinds': {
        'Flutes': [
            'Flute 1',
            'Flute 2',
            'Flute 3'
        ],
        'Saxophones': [
            'Saxophone 2'
        ]
    },
    'Brass': {
        'Trumpets': [
            'Trumpet 1',
            'Trumpet 2',
            'Trumpet 3'
        ],
        'Horns': [
            'F Horn 1',
            'F Horn 2',
            'F Horn 3',
            'F Horn 4',
        ],
        'Baritone': [
             'Baritone'
        ]
    },
};

const songData = {
    'Flute 1': [
        { title: '1. This is Halloween', pdf: 'PDFs/Woodwinds/Flute 1/1. This is Halloween-Flute_1,_2.pdf', audio: 'mp3s/Woodwinds/Flute 1/This is Halloween-Flute_1,_2.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Woodwinds/Flute 1/4. What\'s This - Flute 1.pdf', audio: 'mp3s/Woodwinds/Flute 1/Whats This-Flute_1.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Woodwinds/Flute 1/6. And They Call Him Sandy Claws-Flute.pdf', audio: 'mp3s/Woodwinds/Flute 1/And They Call Him Sandy Claws-Flute.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Woodwinds/Flute 1/8. Sally\'s Song-Flute_1,_2.pdf', audio: 'mp3s/Woodwinds/Flute 1/Sally\'s Song-Flute_1,_2.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Woodwinds/Flute 1/10. Pay the Price Transition-Flute_1,2.pdf', audio: 'mp3s/Woodwinds/Flute 1/Pay the Price-Flute_1,2.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Woodwinds/Flute 1/11. Kidnap The Sandy Claws-Flute.pdf', audio: 'mp3s/Woodwinds/Flute 1/Kidnap The Sandy Claws-Flute.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Woodwinds/Flute 1/16. Oogie Boogie - Flute 1.pdf', audio: 'mp3s/Woodwinds/Flute 1/Oogie Boogies Song-Flute_1.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Woodwinds/Flute 1/18. Christmas Eve Montage-Flute_1,_2.pdf', audio: 'mp3s/Woodwinds/Flute 1/Christmas Eve Montage-Flute_1,_2.mp3' },
        { title: '19. Sally Sneaks', pdf: 'PDFs/Woodwinds/Flute 1/19. Sally Sneaks Transition-Flute_1,2.pdf', audio: 'mp3s/Woodwinds/Flute 1/Sally Sneaks Transition-Flute_1,2.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Woodwinds/Flute 1/20. Sally Gets Caught Flute 1,2.pdf', audio: 'mp3s/Woodwinds/Flute 1/Sally Gets Caught-Flute_1,2.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Woodwinds/Flute 1/25. Finale-Flute_1.pdf', audio: 'mp3s/Woodwinds/Flute 1/Finale-Flute_1.mp3' },
    ],
    'Flute 2': [
        { title: '1. This is Halloween', pdf: 'PDFs/Woodwinds/Flute 2/1. This is Halloween-Flute_1,_2.pdf', audio: 'mp3s/Woodwinds/Flute 2/This is Halloween-Flute_1,_2.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Woodwinds/Flute 2/4. What\'s This - Flute 2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Whats This-Flute_2.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Woodwinds/Flute 2/6. And They Call Him Sandy Claws-Flute.pdf', audio: 'mp3s/Woodwinds/Flute 2/And They Call Him Sandy Claws-Flute.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Woodwinds/Flute 2/8. Sally\'s Song-Flute_1,_2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Sally\'s Song-Flute_1,_2.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Woodwinds/Flute 2/10. Pay the Price Transition-Flute_1,2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Pay the Price-Flute_1,2.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Woodwinds/Flute 2/11. Kidnap The Sandy Claws-Flute.pdf', audio: 'mp3s/Woodwinds/Flute 2/Kidnap The Sandy Claws-Flute.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Woodwinds/Flute 2/16. Oogie Boogie - Flute 2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Oogie Boogies Song-Flute_2.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Woodwinds/Flute 2/18. Christmas Eve Montage-Flute_1,_2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Christmas Eve Montage-Flute_1,_2.mp3' },
        { title: '19. Sally Sneaks', pdf: 'PDFs/Woodwinds/Flute 2/19. Sally Sneaks Transition-Flute_1,2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Sally Sneaks Transition-Flute_1,2.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Woodwinds/Flute 2/20. Sally Gets Caught Flute 1,2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Sally Gets Caught-Flute_1,2.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Woodwinds/Flute 2/25. Finale-Flute_2.pdf', audio: 'mp3s/Woodwinds/Flute 2/Finale-Flute_2.mp3' },
    ],
    'Flute 3': [
    { title: '1. This is Halloween', pdf: 'PDFs/Woodwinds/Flute 3/1. This is Halloween-Oboe_(Opt._Fl._3).pdf', audio: 'mp3s/Woodwinds/Flute 3/This is Halloween-Oboe_(Opt._Fl._3).mp3' },
    { title: "4. What's This", pdf: 'PDFs/Woodwinds/Flute 3/4. What\'s This-Oboe_(Opt._Fl._3).pdf', audio: 'mp3s/Woodwinds/Flute 3/Whats This-Oboe_(Opt._Fl._3).mp3' },
    { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Woodwinds/Flute 3/6. And They Call Him Sandy Claws-Flute.pdf', audio: 'mp3s/Woodwinds/Flute 3/And They Call Him Sandy Claws-Flute.mp3' },
    { title: "8. Sally's Song", pdf: 'PDFs/Woodwinds/Flute 3/8. Sally\'s Song-Oboe_(Opt._Fl._3).pdf', audio: 'mp3s/Woodwinds/Flute 3/Sally\'s Song-Oboe_(Opt._Fl._3).mp3' },
    { title: '10. Pay the Price', pdf: 'PDFs/Woodwinds/Flute 3/10. Pay the Price Transition-Flute_1,2.pdf', audio: 'mp3s/Woodwinds/Flute 3/Pay the Price-Flute_1,2.mp3' },
    { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Woodwinds/Flute 3/11. Kidnap The Sandy Claws-Oboe.pdf', audio: 'mp3s/Woodwinds/Flute 3/Kidnap The Sandy Claws-Oboe.mp3' },
    { title: '16. Oogie Boogie', pdf: 'PDFs/Woodwinds/Flute 3/16. Oogie Boogies Song-Oboe.pdf', audio: 'mp3s/Woodwinds/Flute 3/Oogie Boogies Song-Oboe.mp3' },
    { title: '18. Christmas Eve Montage', pdf: 'PDFs/Woodwinds/Flute 3/18. Christmas Eve Montage-Oboe_(Opt._Fl._3).pdf', audio: 'mp3s/Woodwinds/Flute 3/Christmas Eve Montage-Oboe_(Opt._Fl._3).mp3' },
    { title: '19. Sally Sneaks', pdf: 'PDFs/Woodwinds/Flute 3/19. Sally Sneaks Transition-Flute_1,2.pdf', audio: 'mp3s/Woodwinds/Flute 3/Sally Sneaks Transition-Flute_1,2.mp3' },
    { title: '20. Sally Gets Caught', pdf: 'PDFs/Woodwinds/Flute 3/20. Sally Gets Caught Flute 1,2.pdf', audio: 'mp3s/Woodwinds/Flute 3/Sally Gets Caught-Flute_1,2.mp3' },
    { title: '25. Finale', pdf: 'PDFs/Woodwinds/Flute 3/25. Finale-Oboe.pdf', audio: 'mp3s/Woodwinds/Flute 3/Finale-Oboe.mp3' },
],
    'Saxophone 2': [
        { title: '1. This is Halloween', pdf: 'PDFs/Woodwinds/Alto Sax 2/1. This is Halloween - Alto Saxophone 2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/This is Halloween-Alto_Saxophone_2.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Woodwinds/Alto Sax 2/4. What\'s This - Alto Saxophone 2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Whats This-Alto_Saxophone_2.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Woodwinds/Alto Sax 2/6. And They Call Him Sandy Claws-Alto_Saxophone.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/And They Call Him Sandy Claws-Alto_Saxophone.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Woodwinds/Alto Sax 2/8. Sally\'s Song-Alto_Saxophone_1,_2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Sally\'s Song-Alto_Saxophone_1,_2.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Woodwinds/Alto Sax 2/10. Pay the Price Transition-Eb_Alto_Sax._1,2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Pay the Price-Eb_Alto_Sax._1,2.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Woodwinds/Alto Sax 2/11. Kidnap The Sandy Claws-Alto_Saxophone.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Kidnap The Sandy Claws-Alto_Saxophone.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Woodwinds/Alto Sax 2/16. Oogie Boogie - Alto Sax 2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Oogie Boogies Song-Alto_Sax_2.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Woodwinds/Alto Sax 2/18. Christmas Eve - Alto Saxophone 2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Christmas Eve Montage-Alto_Saxophone_2.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Woodwinds/Alto Sax 2/20. Sally Gets Caught Transition-Eb_Alto_Sax._1,2.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Sally Gets Caught-Eb_Alto_Sax._1,2.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Woodwinds/Alto Sax 2/25. Finale-Alto_Saxophone.pdf', audio: 'mp3s/Woodwinds/Alto Sax 2/Finale-Alto_Saxophone.mp3' },
    ],
    'Trumpet 1': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/Trumpet 1/1. This is Halloween-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/This is Halloween-Bb_Trumpet_1.mp3' },
        { title: '2. Year After Year', pdf: 'PDFs/Brass/Trumpet 1/2. Year After Year-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 1/Year After Year-Bb_Trumpet_1.mp3' },
        { title: '4. What\'s This', pdf: 'PDFs/Brass/Trumpet 1/4. What\'s This - Trumpet 1,2.pdf', audio: 'mp3s/Brass/Trumpet 1/Whats This-Trumpet_1,2.mp3' },
        { title: '8. Sally\'s Song', pdf: 'PDFs/Brass/Trumpet 1/8. Sally\'s Song-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/Sally\'s Song-Bb_Trumpet_1.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Brass/Trumpet 1/10. Pay the Price Transition-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/Pay the Price-Bb_Trumpet_1.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/Trumpet 1/11. Kidnap The Sandy Claws-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/Kidnap The Sandy Claws-Bb_Trumpet_1.mp3' },
        { title: '12. Jack\'s Lament', pdf: 'PDFs/Brass/Trumpet 1/12. Jack\'s Lament-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 1/Jack\'s Lament-Bb_Trumpet_1.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Brass/Trumpet 1/16. Oogie Boogie Bb Trumpet 1.pdf', audio: 'mp3s/Brass/Trumpet 1/Oogie Boogies Song-Bb_Trumpet_1.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/Trumpet 1/18. Christmas Eve Montage-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/Christmas Eve Montage-Bb_Trumpet_1.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/Trumpet 1/20. Sally Gets Caught Transition-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/Sally Gets Caught-Bb_Trumpet_1.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/Trumpet 1/25. Finale-Bb_Trumpet_1.pdf', audio: 'mp3s/Brass/Trumpet 1/Finale-Bb_Trumpet_1.mp3' },
    ],
    'Trumpet 2': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/Trumpet 2/1. This is Halloween-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 2/This is Halloween-Bb_Trumpet_2,_3.mp3' },
        { title: '2. Year After Year', pdf: 'PDFs/Brass/Trumpet 2/2. Year After Year-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 2/Year After Year-Bb_Trumpet_2,_3.mp3' },
        { title: '4. What\'s This', pdf: 'PDFs/Brass/Trumpet 2/4. What\'s This Trumpet 2.pdf', audio: 'mp3s/Brass/Trumpet 2/Whats This-Trumpet_1,2.mp3' },
        { title: '8. Sally\'s Song', pdf: 'PDFs/Brass/Trumpet 2/8. Sally\'s Song-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 2/Sally\'s Song-Bb_Trumpet_2,_3.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Brass/Trumpet 2/10. Pay the Price Transition-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 2/Pay the Price-Bb_Trumpet_2.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/Trumpet 2/11. Kidnap The Sandy Claws-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 2/Kidnap The Sandy Claws-Bb_Trumpet_2.mp3' },
        { title: '12. Jack\'s Lament', pdf: 'PDFs/Brass/Trumpet 2/12. Jack\'s Lament-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 2/Jack\'s Lament-Bb_Trumpet_2,_3.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Brass/Trumpet 2/16. Oogie Boogie Bb Trumpet 2.pdf', audio: 'mp3s/Brass/Trumpet 2/Oogie Boogies Song-Bb_Trumpet_2.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/Trumpet 2/18. Christmas Eve Montage-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 2/Christmas Eve Montage-Bb_Trumpet_2,_3.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/Trumpet 2/20. Sally Gets Caught Transition-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 2/Sally Gets Caught-Bb_Trumpet_2.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/Trumpet 2/25. Finale-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 2/Finale-Bb_Trumpet_2.mp3' },
    ],
    'Trumpet 3': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/Trumpet 3/1. This is Halloween-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 3/This is Halloween-Bb_Trumpet_2,_3.mp3' },
        { title: '2. Year After Year', pdf: 'PDFs/Brass/Trumpet 3/2. Year After Year-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 3/Year After Year-Bb_Trumpet_2,_3.mp3' },
        { title: '4. What\'s This', pdf: 'PDFs/Brass/Trumpet 3/4. What\'s This Trumpet 3.pdf', audio: 'mp3s/Brass/Trumpet 3/Whats This-Trumpet_3.mp3' },
        { title: '8. Sally\'s Song', pdf: 'PDFs/Brass/Trumpet 3/8. Sally\'s Song-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 3/Sally\'s Song-Bb_Trumpet_2,_3.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Brass/Trumpet 3/10. Pay the Price Transition-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 3/Pay the Price-Bb_Trumpet_2.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/Trumpet 3/11. Kidnap The Sandy Claws-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 3/Kidnap The Sandy Claws-Bb_Trumpet_2.mp3' },
        { title: '12. Jack\'s Lament', pdf: 'PDFs/Brass/Trumpet 3/12. Jack\'s Lament-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 3/Jack\'s Lament-Bb_Trumpet_2,_3.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Brass/Trumpet 3/16. Oogie Boogie Bb Trumpet 2.pdf', audio: 'mp3s/Brass/Trumpet 3/Oogie Boogies Song-Bb_Trumpet_2.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/Trumpet 3/18. Christmas Eve Montage-Bb_Trumpet_2,_3.pdf', audio: 'mp3s/Brass/Trumpet 3/Christmas Eve Montage-Bb_Trumpet_2,_3.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/Trumpet 3/20. Sally Gets Caught Transition-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 3/Sally Gets Caught-Bb_Trumpet_2.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/Trumpet 3/25. Finale-Bb_Trumpet_2.pdf', audio: 'mp3s/Brass/Trumpet 3/Finale-Bb_Trumpet_2.mp3' },
    ],
    'F Horn 1': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/F Horn 1/1. This is Halloween-Horn_in_F_1,_2.pdf', audio: 'mp3s/Brass/F Horn 1/This is Halloween-Horn_in_F_1,_2.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Brass/F Horn 1/4. What\'s This Horn in F 1, 2.pdf', audio: 'mp3s/Brass/F Horn 1/Whats This-Horn_in_F_1,_2.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Brass/F Horn 1/6. And They Call Him Sandy Claws - F Horn.pdf', audio: 'mp3s/Brass/F Horn 1/And They Call Him Sandy Claws-F_Horn.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Brass/F Horn 1/8. Sally\'s Song-Horn_in_F_1,_2.pdf', audio: 'mp3s/Brass/F Horn 1/Sally\'s Song-Horn_in_F_1,_2.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Brass/F Horn 1/10. Pay the Price Horn 1, 2.pdf', audio: null },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/F Horn 1/11. Kidnap The Sandy Claws-Horn_in_F.pdf', audio: 'mp3s/Brass/F Horn 1/Kidnap The Sandy Claws-Horn_in_F.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/F Horn 1/18. Christmas Eve Montage-Horn_in_F_1,_2.pdf', audio: 'mp3s/Brass/F Horn 1/Christmas Eve Montage-Horn_in_F_1,_2.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/F Horn 1/20. Sally Gets Caught F Horn.pdf', audio: 'mp3s/Brass/F Horn 1/Sally Gets Caught-F_Horn.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/F Horn 1/25. Finale-Horn_in_F_1,2.pdf', audio: 'mp3s/Brass/F Horn 1/Finale-Horn_in_F_1.mp3' },
    ],
    'F Horn 2': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/F Horn 2/1. This is Halloween-Horn_in_F_1,_2.pdf', audio: 'mp3s/Brass/F Horn 2/This is Halloween-Horn_in_F_1,_2.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Brass/F Horn 2/4. What\'s This Horn in F 1, 2.pdf', audio: 'mp3s/Brass/F Horn 2/Whats This-Horn_in_F_1,_2.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Brass/F Horn 2/6. And They Call Him Sandy Claws - F Horn.pdf', audio: 'mp3s/Brass/F Horn 2/And They Call Him Sandy Claws-F_Horn.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Brass/F Horn 2/8. Sally\'s Song-Horn_in_F_1,_2.pdf', audio: 'mp3s/Brass/F Horn 2/Sally\'s Song-Horn_in_F_1,_2.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Brass/F Horn 2/10. Pay the Price Horn 1, 2.pdf', audio: null },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/F Horn 2/11. Kidnap The Sandy Claws-Horn_in_F.pdf', audio: 'mp3s/Brass/F Horn 2/Kidnap The Sandy Claws-Horn_in_F.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/F Horn 2/18. Christmas Eve Montage-Horn_in_F_1,_2.pdf', audio: 'mp3s/Brass/F Horn 2/Christmas Eve Montage-Horn_in_F_1,_2.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/F Horn 2/20. Sally Gets Caught F Horn.pdf', audio: 'mp3s/Brass/F Horn 2/Sally Gets Caught-F_Horn.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/F Horn 2/25. Finale-Horn_in_F_1,2.pdf', audio: null },
    ],
    'F Horn 3': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/F Horn 3/1. This is Halloween-Horn_in_F_3,_4.pdf', audio: 'mp3s/Brass/F Horn 3/This is Halloween-Horn_in_F_3,_4.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Brass/F Horn 3/4. What\'s This Horn in F 3, 4.pdf', audio: 'mp3s/Brass/F Horn 3/Whats This-Horn_in_F_3,_4.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Brass/F Horn 3/6. And They Call Him Sandy Claws - F Horn.pdf', audio: 'mp3s/Brass/F Horn 3/And They Call Him Sandy Claws-F_Horn.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Brass/F Horn 3/8. Sally\'s Song-Horn_in_F_3,_4.pdf', audio: 'mp3s/Brass/F Horn 3/Sally\'s Song-Horn_in_F_3,_4.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/F Horn 3/11. Kidnap The Sandy Claws-Horn_in_F.pdf', audio: 'mp3s/Brass/F Horn 3/Kidnap The Sandy Claws-Horn_in_F.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/F Horn 3/18. Christmas Eve Montage-Horn_in_F_3,_4.pdf', audio: 'mp3s/Brass/F Horn 3/Christmas Eve Montage-Horn_in_F_3,_4.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/F Horn 3/20. Sally Gets Caught F Horn.pdf', audio: 'mp3s/Brass/F Horn 3/Sally Gets Caught-F_Horn.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/F Horn 3/25. Finale-Horn_in_F_3.4.pdf', audio: 'mp3s/Brass/F Horn 3/Finale-Horn_in_F_2.mp3' },
    ],
    'F Horn 4': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/F Horn 4/1. This is Halloween-Horn_in_F_3,_4.pdf', audio: 'mp3s/Brass/F Horn 4/1. This is Halloween-Horn_in_F_3,_4.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Brass/F Horn 4/4. What\'s This Horn in F 3, 4.pdf', audio: 'mp3s/Brass/F Horn 4/4. What\'s This Horn in F 3, 4.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Brass/F Horn 4/6. And They Call Him Sandy Claws - F Horn.pdf', audio: 'mp3s/Brass/F Horn 4/6. And They Call Him Sandy Claws - F Horn.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Brass/F Horn 4/8. Sally\'s Song-Horn_in_F_3,_4.pdf', audio: 'mp3s/Brass/F Horn 4/8. Sally\'s Song-Horn_in_F_3,_4.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/F Horn 4/11. Kidnap The Sandy Claws-Horn_in_F.pdf', audio: 'mp3s/Brass/F Horn 4/11. Kidnap The Sandy Claws-Horn_in_F.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/F Horn 4/18. Christmas Eve Montage-Horn_in_F_3,_4.pdf', audio: 'mp3s/Brass/F Horn 4/18. Christmas Eve Montage-Horn_in_F_3,_4.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/F Horn 4/20. Sally Gets Caught F Horn.pdf', audio: 'mp3s/Brass/F Horn 4/20. Sally Gets Caught F Horn.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/F Horn 4/25. Finale-Horn_in_F_3.4.pdf', audio: 'mp3s/Brass/F Horn 4/25. Finale-Horn_in_F_3.4.mp3' },
    ],
    'Baritone': [
        { title: '1. This is Halloween', pdf: 'PDFs/Brass/Baritone/1. This is Halloween-Euphonium.pdf', audio: 'mp3s/Brass/Baritone/This is Halloween-Euphonium.mp3' },
        { title: "4. What's This", pdf: 'PDFs/Brass/Baritone/4. What\'s This - Euphonium, Simplified.pdf', audio: 'mp3s/Brass/Baritone/Whats This-Euphonium,_Simplified.mp3' },
        { title: '6. And They Call Him Sandy Claws', pdf: 'PDFs/Brass/Baritone/6. And They Call Him Sandy Claws-Baritone.pdf', audio: 'mp3s/Brass/Baritone/And They Call Him Sandy Claws-Baritone.mp3' },
        { title: "8. Sally's Song", pdf: 'PDFs/Brass/Baritone/8. Sally\'s Song - Euphonium, simplified.pdf', audio: 'mp3s/Brass/Baritone/Sally\'s Song-Euphonium,_simplified.mp3' },
        { title: '10. Pay the Price', pdf: 'PDFs/Brass/Baritone/10. Pay the Price Transition-Baritone.pdf', audio: 'mp3s/Brass/Baritone/Pay the Price-Baritone.mp3' },
        { title: '11. Kidnap The Sandy Claws', pdf: 'PDFs/Brass/Baritone/11. Kidnap The Sandy Claws - Euphonium.pdf', audio: 'mp3s/Brass/Baritone/Kidnap The Sandy Claws-Euphonium.mp3' },
        { title: '16. Oogie Boogie', pdf: 'PDFs/Brass/Baritone/16. Oogie Boogie - Euphonium.pdf', audio: 'mp3s/Brass/Baritone/Oogie Boogies Song-Euphonium.mp3' },
        { title: '18. Christmas Eve Montage', pdf: 'PDFs/Brass/Baritone/18. Christmas Eve Montage-Euphonium.pdf', audio: 'mp3s/Brass/Baritone/Christmas Eve Montage-Euphonium.mp3' },
        { title: '20. Sally Gets Caught', pdf: 'PDFs/Brass/Baritone/20. Sally Gets Caught-Baritone.pdf', audio: 'mp3s/Brass/Baritone/Sally Gets Caught-Baritone.mp3' },
        { title: '25. Finale', pdf: 'PDFs/Brass/Baritone/25. Finale-Euphonium.pdf', audio: 'mp3s/Brass/Baritone/Finale-Euphonium.mp3' },
    ],
};